Benf/feature/obc_iris_handler
AlbertaSat/ex3_software pull request #13
Opened 2024-08-08 02:13 UTC by bsfisher

Created the IRIS handler framework. Currently saves images to a file and does nothing after that, all other commands have output printed directly to the terminal.

Currently opcodes 0-9 are implemented, opcodes 10 and 11 lack sufficient information to know what to expect and have not been written. All opcodes are numbered based off the EX3-SF Software master spreadsheet.

The handler will fail to connect to the current simulated iris subsystem in the main simulated subsystems repository, this is because the port is different on the simulated subsystem compared to the common port. A PR has been made in that repository, those changes need to be implemented for this handler to operate properly.

2024-08-12 20:09 UTC, dheadrick1618 requested changes
Great work! This is awesome. Feels really cool to be able to hand the handler get images from the sim subsystem. 

I requested some minor changes, but other than that this is coming along nicely.

2024-08-12 20:09 UTC, dheadrick1618 commented on scripts/uplink_command_msg.sh
> +gnome-terminal -t SIM_IRIS_SUBSYSTEM -- sh -c "cd $PATH_TO_SIM_SUBS/IRIS && python3 ./iris_simulated_server.py ; bash exec;"
I like this, but I think it may be worth creating a separate script just for testing the IRIS stuff. This is fine as I would like this script to remain as the main one that basically runs the entire FSW, but for convenience testing etc its worth each subsystem having its own script (which still requires the associated sim subsystem, coms handler, and message dispatcher).

2024-08-12 20:09 UTC, dheadrick1618 commented on ex3_obc_fsw/handlers/iris_handler/README.md
> +1. Run the uplink script, details on how to run it are located in the main README for this repository
nitpicky : add link to the readme on github here

2024-08-12 20:09 UTC, dheadrick1618 commented on ex3_obc_fsw/handlers/iris_handler/README.md
> +2. To send commands to the handler, locate the ground station terminal and type ```IRIS <opcode> <arg1> <arg2>...``` the number of arguements required depend on the command.
Just for further clarification to new members reading this - please add some 'example' commands to be entered into the cli GS .

2024-08-13 01:49 UTC, bsfisher commented
I have not implemented to .to() for the IRIS enum yet as there is nothing currently using it and we may decide to use a different method of conversion for the enums at a later point.

2024-08-13 16:09 UTC, dheadrick1618 approved these changes
Great job ! This is coming along nicely. 

nitpicky: the README in the simulated subsystem for IRIS still says port 1821 [ sorry just noticed this] - I think it would probably be best to just link readers to the 'common' lib that contains all the port numbers - that way if they change in the future there is only one source to reference.

2024-08-13 16:09 UTC, dheadrick1618 commented on ex3_obc_fsw/handlers/iris_handler/README.md
Excellent! This is exactly what I wanted. Great work.

2024-08-13 16:09 UTC, dheadrick1618 commented on ex3_shared_libs/common/src/lib.rs
Good job. Now as an enum instead of a pub const, we can use traits to make our lives easier and make the code more readable.

2024-08-13 22:27 UTC, merged