Rowan/feature/implement cli gs bulk protocol
AlbertaSat/ex3_software pull request #14
Opened 2024-08-14 17:08 UTC by rrasmuss4200

Downlink of a large dfgm binary file of simulated data. Breaks into 4KB packets and reassembles on the ground

2024-08-14 17:08 UTC, rrasmuss4200 commented
Might wanna squash some commits?

2024-08-14 20:40 UTC, dheadrick1618 requested changes
Great work so far! Some minor changes request and some feedback that doesn't have to be resolved before merging this PR - just to think about. 

The one thing that is important is to check if your changes break other builds - modifying the fxn signature for the 'new' message constructor breaks everything else that uses it - also the length field should be calculated based on everything else, not provided as a parameter.

2024-08-14 20:40 UTC, dheadrick1618 commented on ex3_shared_libs/message_structure/src/lib.rs
> +    pub fn new(msg_type: u8, msg_id: u8, dest_id: u8, source_id: u8, opcode: u8, msg_len: u16, data: Vec<u8>) -> Self {
The length should be calculated inside the 'new' constructor - otherwise it will be messy having to pre-calculate the length of the message and provide that value as a parameter in this function everytime it is used.

2024-08-14 20:40 UTC, dheadrick1618 commented on ex3_shared_libs/message_structure/src/lib.rs
> +        let header_bytes = &bytes[0..7];
because the '7' is being used more than one place - make this a const defined value at the top of this source file

2024-08-14 22:08 UTC, rrasmuss4200 commented on ex3_obc_fsw/handlers/dfgm_handler/src/main.rs
> +        bulk_msg_dispatcher_interface: Result<IpcClient, std::io::Error>
Right I remember that. Only thing I see with that is that the cmd_msg_disp and the bulk_msg_disp are both servers right now. Would we just make the bulk_msg_disp a client of the cmd_msg_disp and it would have it's own dest_id?

2024-08-14 22:16 UTC, rrasmuss4200 commented on ex3_shared_libs/interfaces/ipc/src/lib.rs
> +                        return Ok(bytes_read);
Would the data on the other client not just be sitting there waiting to be read while the other data is being dealt with? Like the revents in the poll_fd flag would be raised for the next call of the poll function? Or is that not how it works.

2024-08-14 22:16 UTC, rrasmuss4200 commented on ex3_obc_fsw/bulk_msg_dispatcher/README.md
> +5. After the vector of Msg's is ready, it executes a communication protocol with the GS handler for downlinking a large Msg. This protocol can be found [here](https://docs.google.com/document/d/18tPK
:)

2024-08-14 22:20 UTC, rrasmuss4200 commented on ex3_shared_libs/message_structure/src/lib.rs
> +        let header_bytes = &bytes[0..7];
done

2024-08-14 22:20 UTC, rrasmuss4200 commented on ex3_shared_libs/message_structure/src/lib.rs
> +    pub fn new(msg_type: u8, msg_id: u8, dest_id: u8, source_id: u8, opcode: u8, msg_len: u16, data: Vec<u8>) -> Self {
done

2024-08-15 15:56 UTC, dheadrick1618 commented on ex3_shared_libs/interfaces/ipc/src/lib.rs
> +                        return Ok(bytes_read);
I am not sure - this is probably worth testing. I think that makes sense - like the underlying 'plumbing' buffer just holds the data until its read by the next poll - but not sure for how long or how much data that is good for - another issue with this is that if one client keeps getting read it might 'starve' the others that would be read after it because their buffers would keep filling up without being flushed.

2024-08-15 16:13 UTC, dheadrick1618 approved these changes
Everything seems to be working. Great job!

2024-08-15 16:13 UTC, merged