Amar/feature/adcs handler
AlbertaSat/ex3_software pull request #22
Opened 2024-08-23 18:08 UTC by kulovac

Finished a basic version of the ADCS Handler. It currently covers basic error handling and stores data in one file.

2024-08-26 15:42 UTC, rrasmuss4200 requested changes
Could you also make it print the data it gets from the simulated ADCS. Just to make sure that we are getting what we want from the subsystem. It's good that it writes it to a file though. 

Well done so far! It's coming along well

2024-08-26 15:42 UTC, rrasmuss4200 commented on ex3_obc_fsw/handlers/adcs_handler/src/main.rs
> +TODO: move to using `ipc` and not `ipc_interface`
Do this. I deleted the old ipc_interface so now all programs should only use the ipc llb in the interfaces directory.

2024-08-26 15:42 UTC, rrasmuss4200 commented on ex3_obc_fsw/handlers/adcs_handler/src/main.rs
> +        buf.flush();
The ADCS will not have a data toggle. We'll always be able to talk to it whenever we need. The DFGM handler is a bit misleading in this way. I can explain further if needed.

2024-08-26 15:42 UTC, rrasmuss4200 commented on ex3_obc_fsw/handlers/adcs_handler/src/main.rs
> +TODO: move to using `ipc` and not `ipc_interface`
This as in make it use the 'ipc' instead of 'ipc_interface'

2024-08-26 21:17 UTC, kulovac commented on ex3_obc_fsw/handlers/adcs_handler/src/main.rs
> +        buf.flush();
I see, should there be a more general on/off thing, or should I assume the ADCS will always be on?

2024-08-27 00:32 UTC, kulovac commented on ex3_obc_fsw/handlers/adcs_handler/src/main.rs
> +        buf.flush();
I removed the toggle I see what you mean, the DFGM is supposed to be unable to turn off internally, but the ADCS should be able to turn off/on.

2024-08-27 15:12 UTC, rrasmuss4200 commented on ex3_obc_fsw/handlers/adcs_handler/src/main.rs
> +        buf.flush();
Ya, similar to the IRIS handler if you see that one. In reality if should always be on, but we'll have the option to turn it on/off.

2024-08-27 15:12 UTC, rrasmuss4200 commented
Update your branch with main

2024-08-28 16:06 UTC, rrasmuss4200 requested changes
For some reason the logs and adcs_data directories are created within a separate directory inside the adcs handler called ex3_obc_fsw/handlers/adcs_handler/ex3_obc_fsw/handlers/adcs_handler.

This is the same logging path used for the other handlers so unsure why this creates it like this.

Additionally for the merge conflict, you'll need to add both Ron's cmd_handler and yours like this:
```@Rust
ComponentStruct *components[7] = {dfgm_handler, coms_handler, iris_handler, bulk_dispatcher, cmd_handler, test_handler, adcs_handler};
```

2024-08-28 16:26 UTC, kulovac commented
> For some reason the logs and adcs_data directories are created within a separate directory inside the adcs handler called ex3_obc_fsw/handlers/adcs_handler/ex3_obc_fsw/handlers/adcs_handler.
> 
> This is the same logging path used for the other handlers so unsure why this creates it like this.
> 

Yeah, I'm not sure why it's making the directories like that? On my end it seems to work just fine, could it be how you started the handler? I've been using `cargo run --bin adcs_handler` specifically in `ex3_software/`

2024-08-29 16:55 UTC, rrasmuss4200 approved these changes
Everything looks good :)

2024-08-29 16:56 UTC, merged