remove warnings
AlbertaSat/ex3_software pull request #23
Opened 2024-08-25 23:21 UTC by rcunrau

Removed all the warnings, so that everything compiles cleanly now. I didn't look super deep into what I was changing, e.g. if it said a function wasn't called I just deleted it (it's still in git if you ever want it back).

I thought we had enabled clippy in the GitHub workflows, and I actually thought all these errors were generated by clippy in the first place. Just a bit surprised that we weren't flagging the warnings as errors in the build. We can change the cargo build to treat warnings as errors (I think).

2024-08-26 15:01 UTC, rrasmuss4200 requested changes
Thanks for the review and changes Ron. That helps a lot. I'll look into enabling clippy in our workflow and flagging warnings as errors today.

2024-08-26 15:01 UTC, rrasmuss4200 commented on ex3_shared_libs/logging/src/lib.rs
> -use log::{debug, error, info, trace, warn};
Add this to the unit tests. Since we have use super::* in the tests it gets the macros for logging from this import. Now the tests won't run. Interesting how cargo build ignores this...

2024-08-27 03:40 UTC, rcunrau commented on ex3_shared_libs/logging/src/lib.rs
> -use log::{debug, error, info, trace, warn};
I fixed the unit tests, but I had already started on my next set of changes before I realized, i.e. there are now a bunch more changes that are unrelated to the original warnings.

2024-08-27 16:32 UTC, rrasmuss4200 approved these changes
Looks good to go.

2024-08-27 16:33 UTC, merged