Rowan/feature/bring new gs
AlbertaSat/ex3_software pull request #3
Opened 2024-07-14 01:29 UTC by rrasmuss4200

2024-07-14 01:29 UTC, rrasmuss4200 commented
The same as my other pr but with the udated gs. Shoudla made it on the same branch lol

2024-07-15 14:44 UTC, dheadrick1618 requested changes
LGTM once the submodule reference is removed, and a main README is added to the root dir of this repo explaining the contents, and briefly why we put everything from GS and FSW into the same repo.

2024-07-15 14:44 UTC, dheadrick1618 commented on ex3_ground_station/.gitmodules
> +[submodule "ex3_shared_libs"]
Is this still needed, if we are not using submodules anymore?

2024-07-15 14:44 UTC, dheadrick1618 commented on ex3_ground_station/README.md
> +## Workspace Structure
Great job!

2024-07-15 18:33 UTC, dheadrick1618 approved these changes
LGTM. Previous command uplink tall thin demo works. Good job :)

2024-07-15 18:34 UTC, merged